import Link from 'next/link'

export default function AboutPage() {
  return <div className="bg-gray-50">
    <section className="bg-gradient-to-r from-primary-600 to-primary-800 py-16 text-white"><div className="mx-auto max-w-5xl px-4"><p className="text-sm uppercase tracking-widest text-primary-100">About Ilifa</p><h1 className="mt-2 text-4xl font-bold">Building trust into every property journey</h1><p className="mt-5 max-w-3xl text-lg text-primary-100">Ilifa Property Group connects people buying, building and investing in Zimbabwe with properties, contractors, suppliers and practical guidance in one place.</p></div></section>
    <section className="mx-auto grid max-w-5xl gap-8 px-4 py-14 md:grid-cols-2"><div><h2 className="text-2xl font-bold text-gray-900">What we do</h2><p className="mt-4 text-gray-700">We make fragmented property and construction decisions easier to navigate. Users can discover listings, compare professionals and suppliers, request services, and access resources designed for Zimbabwe and the diaspora.</p><p className="mt-4 text-gray-700">Verification indicators improve transparency, but they never replace independent legal advice, title checks, physical inspections, conveyancing or professional due diligence.</p></div><div className="rounded-xl bg-white p-7 shadow"><h2 className="text-2xl font-bold text-gray-900">Our principles</h2><ul className="mt-4 space-y-3 text-gray-700"><li>• Clear information and responsible introductions</li><li>• Safer, more transparent marketplace participation</li><li>• Local expertise with meaningful diaspora support</li><li>• Privacy and security considered from the start</li></ul></div></section>
    <section className="mx-auto max-w-5xl px-4 pb-16"><div className="rounded-xl bg-primary-700 p-8 text-white"><h2 className="text-2xl font-bold">Talk to our team</h2><p className="mt-2 text-primary-100">Questions about buying, building, listing, supplying or partnering with Ilifa?</p><Link href="/contact" className="mt-5 inline-block rounded-lg bg-white px-5 py-3 font-semibold text-primary-700">Contact us</Link></div></section>
  </div>
}
