import Link from 'next/link'

const sections = [
  ['1. Who we are', <>Ilifa Property Group (“Ilifa”, “we”, “us”) operates a Zimbabwe-focused property, construction, professional-services and supplier connection platform. Our address is 3854 Haya Close, Old Windsor, Ruwa, Zimbabwe. Contact us at <a href="mailto:info@ilifapropertygroup.com">info@ilifapropertygroup.com</a> or +44 7471 414983. Ilifa is not a law firm, conveyancer, bank, lender, escrow provider or investment adviser unless a separate written agreement expressly says otherwise.</>],
  ['2. Information we collect', <>We collect information you provide, including your name, contact details, country, account credentials, preferences, enquiries, service requests, listings, messages, verification documents and billing details. We may also receive information from listed members, payment and verification providers, referral partners and public sources. Technical data can include IP address, browser, device, pages visited, referral source, approximate location and cookie identifiers.</>],
  ['3. How and why we use it', <>We use personal information to operate accounts; provide property, contractor, supplier and diaspora workflows; route enquiries at your request; process payments; verify listings and profiles; provide support; prevent fraud and misuse; improve the service; send essential notices; send marketing where permitted; meet legal obligations; and establish or defend legal claims. Our legal basis may be contract, steps requested before a contract, consent, legitimate interests, legal obligation or legal claims, depending on the activity.</>],
  ['4. Sharing information', <>We may share relevant information with the agent, seller, developer, contractor, supplier or professional you choose to contact; and with payment, hosting, IT, communications, analytics, security and verification providers. We may also disclose it to professional advisers, regulators, courts or law enforcement where lawful, or during a business reorganisation. Third parties you contact directly are responsible for their own privacy practices.</>],
  ['5. International transfers', <>Because Ilifa serves Zimbabwe and diaspora users, information may be accessed or transferred across borders. Where applicable law requires it, we use appropriate contractual, organisational and technical safeguards for such transfers.</>],
  ['6. Payments and verification', <>Payment providers process payment credentials under their own policies; Ilifa does not intend to store full card numbers or banking passwords. Verification may involve registration records, certificates, proof of address, identity or property documents and references. A verification indicator does not replace independent legal, title, physical or professional due diligence.</>],
  ['7. Cookies and marketing', <>Necessary cookies support authentication, security and privacy choices. Optional analytics or marketing technologies are used only after the relevant choice. You can change that choice through “Cookie Settings” in the footer. You may opt out of marketing at any time without affecting essential account, security or legal messages. See our <Link href="/cookie-policy">Cookie Policy</Link>.</>],
  ['8. Retention and security', <>We keep information only as long as reasonably required for the service and for legal, tax, accounting, fraud-prevention, verification and dispute records. We then delete, anonymise or securely archive it as appropriate. We use access controls, password protection, secure hosting, restricted staff access and monitoring, but no internet transmission can be guaranteed completely secure.</>],
  ['9. Your rights', <>Depending on applicable law, you may request access, correction, deletion, restriction or portability; object to certain processing or direct marketing; withdraw consent at any time; and complain to the relevant data-protection authority. Withdrawal does not affect earlier lawful processing. Email us to exercise a right; we may first verify your identity.</>],
  ['10. Children and third parties', <>The platform is intended for people aged 18 and over. We do not knowingly collect children’s information and will take reasonable steps to delete it if discovered. Links to external sites, WhatsApp, payment providers and member services are governed by those providers’ own terms and privacy notices.</>],
  ['11. Breaches, changes and contact', <>We investigate personal-data breaches, reduce harm, and notify affected people or authorities when required. We may update this notice and will show a revised date here. Privacy questions and requests can be sent to info@ilifapropertygroup.com, +44 7471 414983, or Ilifa Property Group, 3854 Haya Close, Old Windsor, Ruwa, Zimbabwe. We normally respond within 24 hours.</>],
]

export default function PrivacyPage() { return <div className="bg-gray-50"><section className="bg-gradient-to-r from-primary-600 to-primary-800 py-14 text-white"><div className="mx-auto max-w-5xl px-4"><p className="text-sm uppercase tracking-widest text-primary-100">Legal</p><h1 className="mt-2 text-4xl font-bold">Privacy Policy</h1><p className="mt-4 text-primary-100">Last updated: 31 July 2026</p></div></section><main className="mx-auto max-w-5xl px-4 py-12"><div className="rounded-xl bg-white p-6 shadow sm:p-9"><p className="text-gray-700">This policy explains how Ilifa collects, uses, stores, shares and protects information across its website, accounts, forms, enquiries, listings, directories, verification, payments, WhatsApp and related services.</p>{sections.map(([title, body]) => <section key={title as string} className="mt-8"><h2 className="text-xl font-bold text-gray-900">{title}</h2><div className="mt-3 leading-7 text-gray-700 [&_a]:text-primary-700 [&_a]:underline">{body}</div></section>)}</div></main></div> }
